### ISSUE TITLE
Discrepancies

### ISSUE THREAD

**Issue by Pandorasylvia** [noxone/mahjong-points-calculator-web#138]
I’ve downloaded the mahjong scoring app and also using it online.   But when I enter a hand I’m getting three different scores   Which is the correct one. It’s a doubling problem.

**Comment by Pandorasylvia** [comment]
These are the same hand.    One on iPad.  One on phone.    The phone one is missing Both bonus tiles of the seat wind.  [
![IMG_0007](https://github.com/noxone/mahjong-points-calculator-web/assets/174711531/7442f8d1-82db-4f69-a85b-bcd85fb80e9d)
![IMG_3332](https://github.com/noxone/mahjong-points-calculator-web/assets/174711531/2e6a99db-7d3a-4175-87e4-b87e58605b57)
](url)

**Comment by noxone** [comment]
Hi, thank you for the heads-up.

The iPhone/ iPad version is actually the correct one. I fixed that and then forgot to do the same fixes in the web version.

I will hopefully soon add the fixes to the web-version, too.

**Comment by noxone** [comment]
Should be fixed, as soon as the merge request is built and deployed...
